version: '2'

services:

  solr:
    image: solr:8
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      # NAMED VOLUMES
      - solr_data:/var/solr
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    image: nuremberg:0.15
    tty: true
    command: bash
    volumes:
      # BIND MOUNTS
      - ./:/nuremberg
    environment:
      # let Django load Docker-specific settings conditionally
      - DOCKERIZED=True
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - solr
  selenium:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - "4444:4444"
    environment:
      PORT: 4444
      SCREEN_WIDTH: 1200
      SCREEN_HEIGHT: 900
      SCREEN_DEPTH: 24

  minio:
    image: bitnami/minio:2022.8.22
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-accesskey}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-secretkey}
      - MINIO_DEFAULT_BUCKETS=nuremberg-documents:download,nuremberg-transcripts:download
      # - MINIO_SCHEME=https
    volumes:
      # - ./services/docker/minio/certs:/certs
      - ./minio/data:/data:delegated
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

volumes:
  db_data:
  solr_data:
